### ISSUE TITLE
Text differences from 2e playtest

### ISSUE THREAD

**Issue by milspec74** [jimbodriven/freebooters#1]
This sheet has been essential to my Roll20 game of Freebooters. During play we noticed some differences in the text between this character sheet and the latest playtest rules. For example, in this sheet the magic user "cast spell" still calls for "Mark XP", however the latest playtest rules say "Mark Intelligence".

I am working on updating the text now and will submit the changes in a few weeks.

This is an FYI. Let me know if I am in error, or if you have a more recent version somewhere.

**Comment by jimbodriven** [comment]
Right on, @milspec74 and thank you for the edits. I'm sure your right. 

Glad to hear the sheet is getting used 💪. Happy freebooting!

**Comment by milspec74** [comment]
Here are my text changes to Freebooters.html to align it to the March / April 2018 version of the 2e playtest:

[Freebooters.zip](https://github.com/jimbodriven/freebooters/files/2363174/Freebooters.zip)

**Comment by jimbodriven** [comment]
Committed. Thanks again for the help, @milspec74 !
